javamelody:
    enabled: true


application:
  name: sdyinTest

server:
  port: 9999
  servlet:
    context-path: /
#  ssl:
#    key-store: .keystore
#    key-store-password: lynzsjy311
#    key-store-type: JKS
#    key-alias: tomcat

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
          max-active: 50
          maxTotal: 50
          max-idle: 10
          min-idle: 3
          max-wait: -1
    timeout: 1000
    password:



