javamelody:
    enabled: true


application:
  name: sdyinTest


server:
  port: 9999
  servlet:
    context-path: /
#  ssl:
#    key-store: .keystore
#    key-store-password: lynzsjy311
#    key-store-type: JKS
#    key-alias: tomcat

redis:
  host: 120.79.23.207
  port: 16379
  database: 0
  pool:
      max-active: 50
      maxTotal: 50
      max-idle: 10
      min-idle: 3
      max-wait: -1
      testWhileIdle: true
      minEvictableIdleTimeMillis: 60000
      timeBetweenEvictionRunsMillis: 30000
      numTestsPerEvictionRun: 3
  timeout: 1000



